####################################################
# 配置文件 ~
# 更新于 2020 01 02
####################################################

db_address: "127.0.0.1"
db_port: 27017
db_name: "Tooko"
use_service: false
service: "tooko.service"
bot_token: "1234:XXXX"
def_lang: "简体中文"
fun_prefix:
  - /
  - !
password: ""
public_bot_create: false
bot_create_max: -1
admins:
  - 12345678
log_channel: -10012345678
twitter:
  enable: false
  bot_token: "1234:XXXX"
  public: false
  api_tokens:
    - name: "Tooko for Twitter"
      api_key: ""
      api_secret_key: ""
nsfw_server: http://127.0.0.1:11221
text_censor:
  provider: "baidu"
  app_id: ""
  api_key: ""
  secret_key: ""